import type { Metadata } from "next";
import "@/styles/globals.css";

// const akkurat = localFont({
//     src: "./fonts/AkkuratMono-Regular.ttf",
//     variable: "--font-akkurat",
//     display: "swap",
// });

export const metadata: Metadata = {
    title: "lesgriotsxstudio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="font-mono antialiased"
            >
                {children}
            </body>
        </html>
    );
}
